version: '2'
services:
  sequelize-cursor-psql:
    image: postgres:15.2-alpine
    container_name: sequelize-cursor-psql
    ports:
      - "19132:5432"
    environment:
      # dev database, don't use these in prod!
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    mem_limit: 256M
